L04 02
rhinock/CardManagementService pull request #3
Opened 2021-12-07 22:13 UTC by rhinock

- Added 
  - Entity Framework (EF) Core
  - PostgreSQL DB
  - Repository pattern for interaction with DB
- Removed
  - In-memory data

2022-01-09 07:13 UTC, IgorZudov commented on CMS/Controllers/CardController.cs
> +            _repository.Update(card);
местами пропущены await-ы

2022-01-09 07:14 UTC, IgorZudov requested changes
не нашел файлы миграций

2022-01-09 11:12 UTC, DenisPimenov requested changes

2022-01-09 11:12 UTC, DenisPimenov commented on CMS/AppDbContext.cs
> +            Database.EnsureCreated();
Думаю лишним делать этот вызов при создании контекста каждый раз. В целом мы можем перенести его в метод Startup.Configure\(\). И для большинства приложений обычно достаточно использовать Database.Migrate\(\) тк он проверит что бд существует и убедится что все миграции накатаны на базу

2022-01-09 11:12 UTC, DenisPimenov commented on CMS/Attributes/LoggingAttribute.cs
> +                _log.Info($"{context.HttpContext.Request.Path}");
Лучше объединять подобные логи в один вызов тк при использовании систем агрегаторов логов, вам проще будет искать одну запись в которой будут все данные.

2022-01-09 11:12 UTC, DenisPimenov commented on CMS/Attributes/LoggingAttribute.cs
> +        private readonly ILog _log = LogManager.GetLogger(typeof(LoggingAttribute));
А почему где то используются абстракции логирования MS а где то log4net? И почему выбор пал именно на эту библиотеку?

2022-01-09 11:12 UTC, DenisPimenov commented on CMS/Controllers/CardController.cs
> +        private readonly AppDbContext _appDbContext;
Кажется можно убрать, тк используется абстракция репозитория

2022-01-09 11:12 UTC, DenisPimenov commented on CMS/Middleware/LoggingMiddleware.cs
> +            _logger.LogInformation(
К комментариям выше, лучше стараться использовать шаблонные вызовы логера. _logget.LogInfo("Headers: {h}, Query:{q}, ....", context.Request?.Headers,context.Request?.Query, ...)
На есть две причины:
1. Чаще всего ваш логер будет писать в json формате чтобы потом сохранять если в агрегаторах логов для дальнейшего поиска. И соотвествено они не смогут индексировать ваши данные тк они не будут сохранены в соответствующие поля json.
2. Очень многие логеры (Ms и Serilog как самые распространненные) по умолчанию считают, что вы используете шаблоны и для оптимизации стараются их кешировать. Но когда вы используете интерполяцию при каждом вызове, посути будет кеш промах и вся оптимизация начинает работать против вас.

2022-01-10 18:21 UTC, rhinock commented on CMS/Controllers/CardController.cs
> +            _repository.Update(card);
Исправил в новой версии системы (микросервисной архитектуре):
[CardController.cs](https://github.com/rhinock/CardManagementService/blob/L10-02-02/GatewayService/Controllers/CardController.cs)

2022-01-10 18:24 UTC, rhinock commented
> не нашел файлы миграций

Исправил в новой версии системы ([микросервисной архитектуре](https://github.com/rhinock/CardManagementService/tree/L10-02-02)).

Один из примеров:
- [Migrations](https://github.com/rhinock/CardManagementService/tree/L10-02-02/Data.CardDataService/Migrations)

2022-01-10 18:28 UTC, rhinock commented on CMS/AppDbContext.cs
> +            Database.EnsureCreated();
Исправил в новой версии системы [(микросервисной архитектуре](https://github.com/rhinock/CardManagementService/tree/L10-02-02)).

Один из примеров:
- [Startup.cs](https://github.com/rhinock/CardManagementService/blob/L10-02-02/CardDataService/Startup.cs#L49)
  - [Actualize](https://github.com/rhinock/CardManagementService/blob/L10-02-02/PgDataStore/DataSchema.cs#L21)
    - [Migrate](https://github.com/rhinock/CardManagementService/blob/L10-02-02/Data.CardDataService/MigrationContext.cs#L37)

2022-01-10 18:28 UTC, rhinock commented on CMS/Attributes/LoggingAttribute.cs
> +        private readonly ILog _log = LogManager.GetLogger(typeof(LoggingAttribute));
Исправил в новой версии системы (микросервисной архитектуре).

2022-01-10 18:29 UTC, rhinock commented on CMS/Controllers/CardController.cs
> +        private readonly AppDbContext _appDbContext;
Исправил в новой версии системы (микросервисной архитектуре).

2022-01-10 19:33 UTC, rhinock commented on CMS/Attributes/LoggingAttribute.cs
> +                _log.Info($"{context.HttpContext.Request.Path}");
Исправил в новой версии системы (микросервисной архитектуре):
[LoggingAttribute.cs](https://github.com/rhinock/CardManagementService/blob/L10-02-02/GatewayService/Attributes/LoggingAttribute.cs)

2022-01-10 19:35 UTC, rhinock commented on CMS/Middleware/LoggingMiddleware.cs
> +            _logger.LogInformation(
В новой версии системы (микросервисной архитектуре) логирование перенесено сюда:
[LoggingAttribute.cs](https://github.com/rhinock/CardManagementService/blob/L10-02-02/GatewayService/Attributes/LoggingAttribute.cs)

2022-04-17 16:20 UTC, merged